new Vue({
	el:".container",
	data:{
		limitNum:3,
		addressList:[],
		currentIndex:0,
		shipingMethod:1,
		delFlag:false,
		curProduct:"",
		addFlag:false
	},
	mounted:function(){
		this.$nextTick(function(){
			this.getAddressList();
		});
	},
	computed:{
		filterAddress:function(){
			return this.addressList.slice(0,this.limitNum)
		}
	},
	methods:{
		getAddressList:function(){			
			this.$http.get("data/address.json").then(res=>{			
			// if(res.data.status=="0")			
				this.addressList=res.data.result;			
			});
		},
		loadMore:function(){
			if(this.limitNum==3){
				this.limitNum=this.addressList.length;
			}else{
				this.limitNum=3
			}
		},
		delConfirm:function(item){
			this.delFlag=true;
			this.curProduct=item;
		},
		addConfirm:function(){
			this.addFlag=true;
		},
		delAddress:function(){
			var index=this.addressList.indexOf(this.curProduct);
			this.addressList.splice(index,1)
			this.delFlag=false;
		},
		setDefault:function(addressId){
			console.log(this.addressList)
			this.addressList.forEach(function(address,index){			
				if(address.addressId==addressId){
					address.isDefault=true;
				}else{
					address.isDefault=false;
				}
			})			
		}
	}
});